application: omega-monolith-826
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: static/images

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /susol_mark_resume.pdf
  mime_type: application/pdf
  static_files: static/susol_mark_resume.pdf
  upload: static/susol_mark_resume.pdf

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
