application: omega-monolith-826
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /less
  static_dir: templates/less

- url: /bootstrap
  static_dir: static/bootstrap

- url: /font-awesome
  static_dir: static/font-awesome

- url: /img
  static_dir: static/img

- url: /jquery
  static_dir: static/jquery

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /ulysses.html
  static_files: static/ulysses.html
  upload: static/ulysses.html

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /susol_mark_resume.pdf
  mime_type: application/pdf
  static_files: static/susol_mark_resume.pdf
  upload: static/susol_mark_resume.pdf

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
